#!/usr/bin/python
# -*- coding: UTF-8 -*-
 
for i in range(1,6):
    for j in range(1,6):
        for k in range(1,6):
            if( i != k ) and (i != j) and (j != k):
                print (i,j,k)
